export const SET_IDENTIFY = 'SET_IDENTIFY'
export const SET_IP = 'SET_IP'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_PLAYGAME = 'SET_PLAYGAME'
export const SET_NUMBER = 'SET_NUMBER'
export const SET_ONLINE = 'SET_ONLINE'
export const SET_LOGOUT = 'SET_LOGOUT'
